# Generated by Django 4.2.23 on 2025-07-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pending',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
